[build]
  command = "npm run build"
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"

[build.environment]
  NODE_VERSION = "20"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/stripe/catalog"
  to = "/.netlify/functions/stripe-catalog"
  status = 200

[[redirects]]
  from = "/api/stripe/create-checkout-session"
  to = "/.netlify/functions/stripe-checkout"
  status = 200

[[redirects]]
  from = "/api/stripe/webhook"
  to = "/.netlify/functions/stripe-webhook"
  status = 200
